config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items do
    get 'send_patch_list', on: :member
    post 'prioritize', on: :member
  end
  
  resources :comments
  
  match '/report', to: 'report#report', via: :get
  match '/report', to: 'report#report_email', via: :post
end

app/models/release_item.rb
class ReleaseItem < ActiveRecord::Base
  attr_accessible :release_id, :item_type, :source, :source_reference, :title, :is_config_change, :is_data_change, :affected_product, :level_of_comfort, :level_of_risk, :notes, :modified_by
  
  belongs_to :release, touch: true
  
  validates_presence_of :title, :item_type, :source, :affected_product, :level_of_comfort, :level_of_risk, :notes, :modified_by
  validates_inclusion_of :is_data_change, :is_config_change, in: [true, false]
  validates_length_of :title, maximum: 500
  validates_length_of :notes, maximum: 1000
  
  def self.to_csv(all_release_items)
    CSV.generate do |csv|
      csv << column_names
      all_release_items.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/release_items_controller.rb
class ReleaseItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  def index
    @release = Release.find(params[:id])
    @release_items = ReleaseItem.find(:all, select: "release_items.*, users.email, users.name", joins: "LEFT JOIN users ON users.email = release_items.modified_by", conditions: ["release_items.release_id = ?", params[:id]], order: "release_items.item_type ASC, release_items.priority ASC, release_items.id ASC")
    @release_items_levels_averages = ReleaseItem.find(:all, select: "ROUND(AVG(level_of_risk)) AS risk_level_average, ROUND(AVG(level_of_comfort)) AS comfort_level_average", conditions: ["release_id = ?", params[:id]]).first
    @items_data, @items_general, @items_patch, @items_project, @items_upgrade = [], [], [], [], []
    @release_items.each do |item|
      @items_data << item if item.item_type == 'Data'
      @items_general << item if item.item_type == 'General'
      @items_patch << item if item.item_type == 'Patch'
      @items_project << item if item.item_type == 'Project'
      @items_upgrade << item if item.item_type == 'Upgrade'
    end
    @release_item_types = [['General', @items_general], ['Project', @items_project], ['Upgrade', @items_upgrade], ['Data', @items_data], ['Patch', @items_patch]]
    respond_to do |format|
      format.html
      format.csv { send_data ReleaseItem.to_csv(@release_items) }
    end
  end
  
  def new
    @release_item = ReleaseItem.new
    @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", 1], order: "priority ASC")
    @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", 1], order: "category ASC, label ASC")
    @designs_acura, @designs_asbury, @designs_bmw, @designs_dealer, @designs_facebook, @designs_ford, @designs_fusion, @designs_gsm, @designs_infiniti, @designs_lincoln, @designs_mobile, @designs_nissan, @designs_scion, @designs_tools, @designs_general = [], [], [], [], [], [], [], [], [], [], [], [], [], [], []
    @affected_designs_data.each do |design|
      @designs_acura << design if design.category == 'Acura'
      @designs_asbury << design if design.category == 'Asbury'
      @designs_bmw << design if design.category == 'BMW'
      @designs_dealer << design if design.category == 'Dealer'
      @designs_facebook << design if design.category == 'Facebook'
      @designs_ford << design if design.category == 'Ford'
      @designs_fusion << design if design.category == 'Fusion'
      @designs_gsm << design if design.category == 'GSM'
      @designs_infiniti << design if design.category == 'Infiniti'
      @designs_lincoln << design if design.category == 'Lincoln'
      @designs_mobile << design if design.category == 'Mobile'
      @designs_nissan << design if design.category == 'Nissan'
      @designs_scion << design if design.category == 'Scion'
      @designs_tools << design if design.category == 'Tools'
      @designs_general << design if design.category == 'General'
    end
    @affected_designs = [['Acura', @designs_acura], ['Asbury', @designs_asbury], ['BMW', @designs_bmw], ['Dealer', @designs_dealer], ['Facebook', @designs_facebook], ['Ford', @designs_ford], ['Fusion', @designs_fusion], ['GSM', @designs_gsm], ['Infiniti', @designs_infiniti], ['Lincoln', @designs_lincoln], ['Mobile', @designs_mobile], ['Nissan', @designs_nissan], ['Scion', @designs_scion], ['Tools', @designs_tools], ['General', @designs_general]]
  end
  
  def create
    @release_item = ReleaseItem.new(params[:release_item])
    affected_browsers = params[:affected_browsers]
    affected_designs = params[:affected_designs]
    if affected_browsers
	    @release_item.affected_browsers = affected_browsers.join(", ")
	  end
	  if affected_designs
      @release_item.affected_designs = affected_designs.join(", ")
    end
    if @release_item.save
      flash[:success] = "\"#{@release_item.title}\" has been created as a new release item."
      redirect_to release_items_path(id: @release_item.release_id)
    else
      @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", 1], order: "priority ASC")
      @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", 1], order: "category ASC, label ASC")
      @designs_acura, @designs_asbury, @designs_bmw, @designs_dealer, @designs_facebook, @designs_ford, @designs_fusion, @designs_gsm, @designs_infiniti, @designs_lincoln, @designs_mobile, @designs_nissan, @designs_scion, @designs_tools, @designs_general = [], [], [], [], [], [], [], [], [], [], [], [], [], [], []
      @affected_designs_data.each do |design|
        @designs_acura << design if design.category == 'Acura'
        @designs_asbury << design if design.category == 'Asbury'
        @designs_bmw << design if design.category == 'BMW'
        @designs_dealer << design if design.category == 'Dealer'
        @designs_facebook << design if design.category == 'Facebook'
        @designs_ford << design if design.category == 'Ford'
        @designs_fusion << design if design.category == 'Fusion'
        @designs_gsm << design if design.category == 'GSM'
        @designs_infiniti << design if design.category == 'Infiniti'
        @designs_lincoln << design if design.category == 'Lincoln'
        @designs_mobile << design if design.category == 'Mobile'
        @designs_nissan << design if design.category == 'Nissan'
        @designs_scion << design if design.category == 'Scion'
        @designs_tools << design if design.category == 'Tools'
        @designs_general << design if design.category == 'General'
      end
      @affected_designs = [['Acura', @designs_acura], ['Asbury', @designs_asbury], ['BMW', @designs_bmw], ['Dealer', @designs_dealer], ['Facebook', @designs_facebook], ['Ford', @designs_ford], ['Fusion', @designs_fusion], ['GSM', @designs_gsm], ['Infiniti', @designs_infiniti], ['Lincoln', @designs_lincoln], ['Mobile', @designs_mobile], ['Nissan', @designs_nissan], ['Scion', @designs_scion], ['Tools', @designs_tools], ['General', @designs_general]]
      render 'new'
    end
  end
  
  def edit
    @release_item = ReleaseItem.find(params[:id])
    @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", 1], order: "priority ASC")
    @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", 1], order: "category ASC, label ASC")
    @designs_acura, @designs_asbury, @designs_bmw, @designs_dealer, @designs_facebook, @designs_ford, @designs_fusion, @designs_gsm, @designs_infiniti, @designs_lincoln, @designs_mobile, @designs_nissan, @designs_scion, @designs_tools, @designs_general = [], [], [], [], [], [], [], [], [], [], [], [], [], [], []
    @affected_designs_data.each do |design|
      @designs_acura << design if design.category == 'Acura'
      @designs_asbury << design if design.category == 'Asbury'
      @designs_bmw << design if design.category == 'BMW'
      @designs_dealer << design if design.category == 'Dealer'
      @designs_facebook << design if design.category == 'Facebook'
      @designs_ford << design if design.category == 'Ford'
      @designs_fusion << design if design.category == 'Fusion'
      @designs_gsm << design if design.category == 'GSM'
      @designs_infiniti << design if design.category == 'Infiniti'
      @designs_lincoln << design if design.category == 'Lincoln'
      @designs_mobile << design if design.category == 'Mobile'
      @designs_nissan << design if design.category == 'Nissan'
      @designs_scion << design if design.category == 'Scion'
      @designs_tools << design if design.category == 'Tools'
      @designs_general << design if design.category == 'General'
    end
    @affected_designs = [['Acura', @designs_acura], ['Asbury', @designs_asbury], ['BMW', @designs_bmw], ['Dealer', @designs_dealer], ['Facebook', @designs_facebook], ['Ford', @designs_ford], ['Fusion', @designs_fusion], ['GSM', @designs_gsm], ['Infiniti', @designs_infiniti], ['Lincoln', @designs_lincoln], ['Mobile', @designs_mobile], ['Nissan', @designs_nissan], ['Scion', @designs_scion], ['Tools', @designs_tools], ['General', @designs_general]]
  end
  
  def update
    @release_item = ReleaseItem.find(params[:id])
    affected_browsers = params[:affected_browsers]
    affected_designs = params[:affected_designs]
    if affected_browsers
	    @release_item.affected_browsers = affected_browsers.join(", ")
	  end
	  if affected_designs
      @release_item.affected_designs = affected_designs.join(", ")
    end
    if @release_item.update_attributes(params[:release_item])
      redirect_to release_items_path(id: @release_item.release_id)
      flash[:success] = "\"#{@release_item.title}\" has been updated!"
    else
      @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", 1], order: "priority ASC")
      @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", 1], order: "category ASC, label ASC")
      @designs_acura, @designs_asbury, @designs_bmw, @designs_dealer, @designs_facebook, @designs_ford, @designs_fusion, @designs_gsm, @designs_infiniti, @designs_lincoln, @designs_mobile, @designs_nissan, @designs_scion, @designs_tools, @designs_general = [], [], [], [], [], [], [], [], [], [], [], [], [], [], []
      @affected_designs_data.each do |design|
        @designs_acura << design if design.category == 'Acura'
        @designs_asbury << design if design.category == 'Asbury'
        @designs_bmw << design if design.category == 'BMW'
        @designs_dealer << design if design.category == 'Dealer'
        @designs_facebook << design if design.category == 'Facebook'
        @designs_ford << design if design.category == 'Ford'
        @designs_fusion << design if design.category == 'Fusion'
        @designs_gsm << design if design.category == 'GSM'
        @designs_infiniti << design if design.category == 'Infiniti'
        @designs_lincoln << design if design.category == 'Lincoln'

app/helpers/release_items_helper.rb
module ReleaseItemsHelper
  def build_source_url(source, ref)
    if source == "FogBugz"
      "<a href='https://clickmotive.fogbugz.com/default.asp?#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    elsif source == "VersionOne"
      "<a href='https://www10.v1host.com/ClickMotive/Search.mvc/advanced?q=#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    elsif source == "ZenDesk"
      "<a href='http://clickmotive.zendesk.com/tickets/#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    end
  end
  
  def convert_risk_level_to_words(level)
    if level == "1" || level == 1.0
      "<span class='low-risk'>Low Risk</span>".html_safe
    elsif level == "2" || level == 2.0
      "<span class='medium-risk'>Medium Risk</span>".html_safe
    elsif level == "3" || level == 3.0
      "<span class='high-risk'>High Risk</span>".html_safe
    end
  end
  
  def convert_comfort_level_to_words(level)
    if level == "1" || level == 1.0
      "<span class='low-comfort'>Low Comfort</span>".html_safe
    elsif level == "2" || level == 2.0
      "<span class='medium-comfort'>Medium Comfort</span>".html_safe
    elsif level == "3" || level == 3.0
      "<span class='high-comfort'>High Comfort</span>".html_safe
    end
  end
end

app/views/release_items/_edit_form.html.erb
<script type="text/javascript">
	var checked = function checked(){
		$('input:checked').parent().addClass('checked');
		$('input:not(:checked)').parent().removeClass('checked');
	}
	
	var checkAll = function checkAll(section){
		$('label[data-category="' + section + '"]').find('input').each(function(){
			if($(this).is(':checked') || $(this).attr('checked') == false){
				$(this).prop('checked', false);
				checked();
			} else {
				$(this).prop('checked', true);
				checked();
			}
		});
	}
	
	$(window).load(function(){
		$('input[type="checkbox"]').click(function(){
			checked();
		});
		
		checked();
	});
</script>
<%= form_for(@release_item) do |f| %>
	<%= render 'shared/error_messages', :object => @release_item %>
	
	<%= f.label :item_type, "Type*" %>
	<%= f.select :item_type, options_for_select(["Data","General","Patch","Project","Upgrade"], selected: @release_item.item_type) %>
	
	<%= f.label :source, "Source*" %>
	<%= f.select :source, options_for_select(["FogBugz","VersionOne","ZenDesk"], selected: @release_item.source) %>
	
	<%= f.label :source_reference, "Source Reference" %>
	<%= f.text_field :source_reference, placeholder: "Enter ID...", class: "input-medium" %>
	
	<%= f.label :title, "Title*" %>
	<%= f.text_field :title, placeholder: "Enter the release item title...", class: "input-xxlarge" %>
	
	<%= f.label :is_data_change, "Data Change?*" %>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, false %> no</label>
	
	<%= f.label :is_config_change, "Config Change?*", class: "config-change" %>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, false %> no</label>
   	
   	<div class="release-item-affected-browsers">
	   	<h3>Affected Browsers?<h3>
	   	<div class="affected-browsers-list">
		   	<% for browser in @affected_browsers_data %>
		   		<label>
		   			<% if @release_item.affected_browsers.split(", ").collect(&:strip).include? browser.browser %>
			   			<%= check_box_tag "affected_browsers[]", browser.browser, true %> <%= browser.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_browsers[]", browser.browser %> <%= browser.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
			<div class="clearfix"></div>
	   	</div>
   	</div>
   	<div class="release-item-affected-designs">
	   	<h3>Affected Designs?</h3>
	   	<div class="affected-designs-list">
		   	<% for category in @affected_designs %>
			   	<div class="affected-designs-list-heading">
			   		<%= category[0] %> (<span class="check-all" onclick="checkAll('<%= category[0] %>');">check/uncheck all</span>)
			   	</div>
			   	<% for design in category[1] %>
			   		<label data-category="<%= design.category %>">
			   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
				   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.design %>
				   		<% else %>
				   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.design %>
				   		<% end %>
				   	</label>
			   	<% end %>
			<% end %>
			<div class="clearfix"></div>
	   	</div>
   	</div>
	
	<%= f.label :affected_product, "Affected Product*" %>
	<%= f.select :affected_product, options_for_select(["N/A","Asset Server","Flex","Fusion Website","Inventory Process","New Relic","MVC"], selected: @release_item.affected_product) %>
	
	<%= f.label :level_of_risk, "Risk Level*" %>
	<%= f.select :level_of_risk, [["low",1],["medium",2],["high",3]], { include_blank: '' } %>
	
	<%= f.label :level_of_comfort, "Comfort Level*" %>
	<%= f.select :level_of_comfort, [["high",3],["medium",2],["low",1]], { include_blank: '' } %>
    
    <%= f.label :notes, "Notes" %>
	<%= f.text_field :notes, placeholder: "Enter notes for this item...", class: "input-xxlarge" %>
    
    <%= f.hidden_field :modified_by, value: current_user.email %>
	
	<div class="form-action-buttons">
		<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<div class="btn-cancel">
			<%= link_to "Cancel", :back, class: "btn btn-large" %>
		</div>
	</div>
<% end %>

app/views/release_items/_new_form.html.erb
<script type="text/javascript">
	var checked = function checked(){
		$('input:checked').parent().addClass('checked');
		$('input:not(:checked)').parent().removeClass('checked');
	}
	
	var checkAll = function checkAll(section){
		$('label[data-category="' + section + '"]').find('input').each(function(){
			if($(this).is(':checked') || $(this).attr('checked') == false){
				$(this).prop('checked', false);
				checked();
			} else {
				$(this).prop('checked', true);
				checked();
			}
		});
	}
	
	$(window).load(function(){
		$('input[type="checkbox"]').click(function(){
			checked();
		});
		
		checked();
	});
</script>
<%= form_for(@release_item) do |f| %>
	<%= render 'shared/error_messages', :object => @release_item %>
	
	<%= f.label :item_type, "Type*" %>
	<%= f.select :item_type, options_for_select(["Data","General","Patch","Project","Upgrade"], "General") %>
	
	<%= f.label :source, "Source*" %>
	<%= f.select :source, options_for_select(["FogBugz","VersionOne","ZenDesk"], "VersionOne") %>
	
	<%= f.label :source_reference, "Source Reference" %>
	<%= f.text_field :source_reference, placeholder: "Enter ID...", class: "input-medium" %>
	
	<%= f.label :title, "Title*" %>
	<%= f.text_field :title, placeholder: "Enter the release item title...", class: "input-xxlarge" %>
	
	<%= f.label :is_data_change, "Data Change?*" %>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, false, checked: true %> no</label>
	
	<%= f.label :is_config_change, "Config Change?*", class: "config-change" %>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, false, checked: true %> no</label>
   	
   	<div class="release-item-affected-browsers">
	   	<h3>Affected Browsers?</h3>
	   	<div class="affected-browsers-list">
		   	<% for browser in @affected_browsers_data %>
		   		<label>
		   			<%= check_box_tag "affected_browsers[]", browser.browser %> <%= browser.label %>
			   	</label>
		   	<% end %>
			<div class="clearfix"></div>
		</div>
	</div>

	<div class="release-item-affected-designs">
	   	<h3>Affected Designs?</h3>
	   	<div class="affected-designs-list">
	   		<% for category in @affected_designs %>
			   	<div class="affected-designs-list-heading">
			   		<%= category[0] %> (<span class="check-all" onclick="checkAll('<%= category[0] %>');">check/uncheck all</span>)
			   	</div>
			   	<% for design in category[1] %>
			   		<label data-category="<%= design.category %>">
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.design %>
				   	</label>
			   	<% end %>
			<% end %>
			<div class="clearfix"></div>
		</div>
	</div>
	
	<%= f.label :affected_product, "Affected Product*" %>
	<%= f.select :affected_product, options_for_select(["N/A","Asset Server","Flex","Fusion Website","Inventory Process","New Relic","MVC"], "N/A") %>
	
	<%= f.label :level_of_risk, "Risk Level*" %>
	<%= f.select :level_of_risk, [["low",1],["medium",2],["high",3]], { include_blank: '' } %>
	
	<%= f.label :level_of_comfort, "Comfort Level*" %>
	<%= f.select :level_of_comfort, [["high",3],["medium",2],["low",1]], { include_blank: '' } %>
    
    <%= f.label :notes, "Notes" %>
	<%= f.text_field :notes, placeholder: "Enter notes for this item...", class: "input-xxlarge" %>
    
    <%= f.hidden_field :modified_by, value: current_user.email %>
    <% if params[:id] %>
	    <%= f.hidden_field :release_id, value: params[:id] %>
	<% else %>
		<%= f.hidden_field :release_id, value: @release_item.release_id %>
	<% end %>
	
	<div class="form-action-buttons">
		<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<div class="btn-cancel">
			<%= link_to "Cancel", :back, class: "btn btn-large" %>
		</div>
	</div>
<% end %>

app/views/release_items/_release_items.html.erb
<article id="item_<%= item.id %>" class="data sortable">
	<div class="item-title">
		<%= build_source_url(item.source, item.source_reference) if item.source_reference? %><%= (item.is_data_change == true || item.is_config_change == true) ? "<span class='important-item'>#{item.title}</span>".html_safe : item.title %>
		<div class="item-title-actions">
			<% if user_signed_in? %>
				<%= link_to "Update", edit_release_item_path(item), class: "btn btn-small btn-primary" %>
				<%= link_to "Delete", item, method: :delete, data: { confirm: "Are you sure you want to delete #{item.title}?" }, class: "btn btn-small" %>
			<% end %>
		</div>
		<% if user_signed_in? && current_user.show_timestamps == true %>
			<%= "<div class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</div>".html_safe unless item.modified_by.blank? %>
		<% end %>
	</div>
	<div class="item-details">
		<!--
			Disabling the collapsing functionality for now
			so that I can push this out to production now.
			
			TODO: Finish this functionality later.
			
				<h4><a class="collapsible-link" href="#" onclick="collapseDetails(<%= item.id %>); return false;">Details -</a></h4>
		-->
		
		<div class="collapsible">
			<span class="headings">Risk Level:</span> <%= convert_risk_level_to_words(item.level_of_risk) %><br />
			<span class="headings">Comfort Level:</span> <%= convert_comfort_level_to_words(item.level_of_comfort) %><br />
			<span class="headings">Data Change?</span> <%= item.is_data_change? ? "yes" : "no" %><br />
			<span class="headings">Config Change?</span> <%= item.is_config_change? ? "yes" : "no" %><br />
			<span class="headings">Affected Product:</span> <%= item.affected_product %><br />
			<span class="headings">Affected Browser(s):</span> <%= item.affected_browsers %><br />
			<span class="headings">Affected Design(s):</span> <%= item.affected_designs %><br />
			<span class="headings">Date Added:</span> <%= item.created_at.strftime('%B %e, %Y @ %l:%M %P') %><br />
		</div>
		<div class="well">
			<span class="headings">Notes:</span> <%= item.notes %>
		</div>
	</div>
</article>

app/views/release_items/edit.html.erb
<% provide(:title, 'Update Release Item') %>

<h1>
	Update Release Item
</h1>

<%= render 'edit_form' %>

app/views/release_items/index.html.erb
<% provide(:title, "Release Items for: #{@release.title}") %>

<% if @release.archive == true %>
	<div class="label label-warning archive-tag">
		Archived
	</div>
<% end %>
<h1>
	Release Items for: <%= @release.title %><br />
	<%= link_to "View the Checklist for this Release", checklist_path(@release.id), class: "btn btn-small" %>
</h1>

<div class="release-details">
	<div class="left-column">
		<span class="headings">Primary Contact:</span> <%= (@release.contact != '') ? @release.contact : 'Unassigned' %><br />
		<span class="headings">Backup Contact:</span> <%= (@release.backup_contact != '') ? @release.backup_contact : 'Unassigned' %><br />
		<span class="headings">Risk Level:</span> <%= convert_risk_level_to_words(@release_items_levels_averages.risk_level_average) %><br />
		<span class="headings">Comfort Level:</span> <%= convert_comfort_level_to_words(@release_items_levels_averages.comfort_level_average) %><br />
		<span class="headings">Release Date:</span> <%= (@release.release_date) ? @release.release_date.strftime('%B %e, %Y') : 'Not Specified' %><br />
		<span class="headings">Code Cutoff Date:</span> <%= (@release.code_cutoff_date) ? @release.code_cutoff_date.strftime('%B %e, %Y') : 'Not Specified' %>
	</div>
	<div class="right-column">
		<span class="headings">Total Items in this Release:</span> <%= @release_items.count unless @release_items.nil? %><br />
		<span class="headings">Breakdown:</span> (Data: <%= @items_data.count unless @items_data.nil? %>, General: <%= @items_general.count unless @items_general.nil? %>, Patches: <%= @items_patch.count unless @items_patch.nil? %>, Projects: <%= @items_project.count unless @items_project.nil? %>, Upgrades: <%= @items_upgrade.count unless @items_upgrade.nil? %>)
		<div class="export-to-csv">
			<%= link_to "Export List to CSV", release_items_path(id: @release.id, format: 'csv'), class: "btn btn-small" %>
			<% if user_signed_in? && @release.release_date > Date.today %>
				<% if @items_patch.count == 0 %>
					<%= link_to "Email Patch List", send_patch_list_release_item_path(id: @release.id), class: "btn btn-small", disabled: "disabled" %>
				<% else %>
					<%= link_to "Email Patch List", send_patch_list_release_item_path(id: @release.id), class: "btn btn-small" %>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="release-add-new-jump-to">
	<% if user_signed_in? %>
		<%= link_to "Add New Release Item", new_release_item_path(id: params[:id]), class: "btn btn-large btn-primary btn-new-release-item" %>
	<% end %>
	<div class="jump-to-item">
		<strong>Go Directly To: </strong>
		<% for items in @release_item_types %>
			<%= link_to "#{items[0]} Items", "##{items[0]}Items" %>
			<%= "&nbsp;&nbsp;|&nbsp;&nbsp;".html_safe unless items == @release_item_types.last %>
		<% end %>
	</div>
</div>

<!--
	Disabling the collapsing functionality for now
	so that I can push this out to production now.
	
	TODO: Finish this functionality later.
	
		<div class="collapse-all-links">
			<a class="collapse-all-up" onclick="collapseAllDetailsUp(); return false;">Hide All Release Item Details -</a>
			<a class="collapse-all-down hide" onclick="collapseAllDetailsDown(); return false;">Show All Release Item Details +</a>
		</div>
-->

<% for items in @release_item_types %>
	<a name="<%= items[0] %>Items"></a>
	<fieldset class="release-items">
		<legend>
			<%= items[0] %> Items
			<span class="back-to-top">[<a href="#top">back to top</a>]</span>
		</legend>
		<section class="data-list release-items-list">
			<% if items[1].empty? %>
				<h2>There are no general items in this release.</h2>
			<% else %>
				<% items[1].each do |item| %>
					<%= render 'release_items', item: item %>
				<% end %>
			<% end %>
		</section>
		<div class="clearfix"></div>
	</fieldset>
<% end %>

<% if user_signed_in? %>
	<%= link_to "Add New Release Item", new_release_item_path(id: params[:id]), class: "btn btn-large btn-primary btn-new-release-item" %>
<% end %>

app/views/release_items/new.html.erb
<% provide(:title, 'Create New Release Item') %>

<h1>
	Create New Release Item
</h1>

<%= render 'new_form' %>