config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items do
    get 'send_patch_list', on: :member
    post 'prioritize', on: :member
  end
  
  resources :comments
  
  match '/report', to: 'report#report', via: :get
  match '/report', to: 'report#report_email', via: :post
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  
  def show
    @release = Release.find(params[:id])
    @checklist_tools = ChecklistTool.find(:all, joins: :release_data, conditions: ["checklist_tools.release_id = ?", params[:id]], order: "checklist_tools.release_data_id ASC")
    @checklist_development_items = ChecklistItem.find(:all, select: "checklist_items.*, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "development"], group: "checklist_items.id", order: "checklist_items.id ASC")
    @checklist_stage_items = ChecklistItem.find(:all, select: "checklist_items.*, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "stage"], group: "checklist_items.id", order: "checklist_items.id ASC")
    @checklist_production_items = ChecklistItem.find(:all, select: "checklist_items.*, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "production"], group: "checklist_items.id", order: "checklist_items.id ASC")
    @projects = ReleaseItem.find(:all, select: "release_items.*, users.email, users.name, COUNT(comments.id) AS comments_count", joins: ["LEFT OUTER JOIN comments ON comments.checklist_item_id = release_items.id", "LEFT JOIN users ON users.email = release_items.modified_by"], conditions: ["release_items.item_type = ? AND release_items.release_id = ?", 'Project', params[:id]], group: "release_items.id")
    @project_comments = Comment.find(:all, conditions: ["release_id = ? AND checklist_item_type = ?", params[:id], 'Project'])
    @environments = ["development","stage","production","projects"]
  end
  
  def toggle_tool
    @tool = ChecklistTool.find(params[:id])
    @tool.toggle!(:value)
    @tool.update_column(:modified_by, current_user.email)
    respond_to do |format|
      format.js
	  end
  end
  
  def toggle_item
    @item = ChecklistItem.find(params[:id])
    @item.toggle!(:value)
    @item.update_column(:modified_by, current_user.email)
    render nothing: true
  end
  
  def toggle_applicable
    @item = ChecklistItem.find(params[:id])
    @item.toggle!(:applicable)
    @item.update_column(:modified_by, current_user.email)
    respond_to do |format|
      format.js
	  end
  end
  
  def destroy
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.destroy
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
	def toggle_tool(tool)
	  tool.value? ? "<a href='/checklists/#{tool.id}/toggle_tool' data-remote='true' id='checklist_tool_#{tool.id}' class='tool-affected'>#{tool.release_data.label}</a>".html_safe : "<a href='/checklists/#{tool.id}/toggle_tool' data-remote='true' id='checklist_tool_#{tool.id}' class='tool-not-affected'>#{tool.release_data.label}</a>".html_safe
	end
	
	def toggle_item_checkbox(item)
	  @environment = "'#{item.environment}'"
	  if user_signed_in?
      @disabled = ""
	  else
	    @disabled = "disabled='disabled'"
	  end
	  
		if item.value == true
		  if item.applicable == true
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" checked='checked' #{@disabled} /> #{item.release_data.label}".html_safe
		  elsif item.applicable == false
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" checked='checked' disabled='disabled' /> #{item.release_data.label}".html_safe
		  end
    elsif item.value == false
		  if item.applicable == true
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" #{@disabled} /> #{item.release_data.label}".html_safe
		  elsif item.applicable == false
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" disabled='disabled' /> #{item.release_data.label}".html_safe
		  end
	  end
	end
	
	def toggle_applicable(item)
		item.applicable? ? "<img src='/assets/iconNotApplicable.png' alt='Not Applicable' /> Mark Not Applicable".html_safe : "<img src='/assets/iconSave.png' alt='Applicable' /> Mark Applicable".html_safe
	end
end

app/views/checklists/show.html.erb
<% provide(:title, "Checklist for: #{@release.title}") %>
<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			padding: 20,
			scrolling: 'no',
			maxWidth: 700,
			afterClose: function() { parent.location.reload(true); }
		});
	});
</script>

<% if @release.archive == true %>
	<div class="label label-warning archive-tag">
		Archived
	</div>
<% end %>
<h1>
	Checklist for: <%= @release.title %><br />
	<%= link_to "View the Release List for this Release", release_items_path(id: @release.id), class: "btn btn-small" %>
</h1>

<div class="checklist-release-details">
	<span class="headings">Primary Contact:</span> <%= (@release.contact != '') ? @release.contact : 'Unassigned' %><br />
	<span class="headings">Backup Contact:</span> <%= (@release.backup_contact != '') ? @release.backup_contact : 'Unassigned' %><br />
	<span class="headings">Release Date:</span> <%= (@release.release_date) ? @release.release_date.strftime('%B %e, %Y') : 'Not Specified' %><br />
	<span class="headings">Code Cutoff Date:</span> <%= (@release.code_cutoff_date) ? @release.code_cutoff_date.strftime('%B %e, %Y') : 'Not Specified' %>
</div>
<div class="checklist-affected-tools">
	<h3>
		Affected Tools
	</h3>
	<% @checklist_tools.each do |tool| %>
		<div class="tool">
			<% if user_signed_in? %>
				<%= toggle_tool(tool) %>
			<% else %>
				<%= toggle_tool_image(tool) %>
			<% end %>
		</div>
	<% end %>
</div>
<% @environments.each do |environment| %>
	<div class="checklist-<%= environment %>">
		<h3>
			<%= environment.capitalize %> Branch
			<% if user_signed_in? && environment != "projects" %>
				<span class="status"></span>
			<% end %>
		</h3>
		<%
			if environment == "development"
				@list_items = @checklist_development_items
			elsif environment == "stage"
				@list_items = @checklist_stage_items
			elsif environment == "production"
				@list_items = @checklist_production_items
			elsif environment == "projects"
				@list_items = @projects
			end
		%>
		<% if environment == "projects" && @projects.empty? %>
			<h2>There are no projects in this release.</h2>
		<% else %>
			<% @list_items.each do |item| %>
				<%
					if environment == "projects"
						@item_comments = @project_comments
					else
						@item_comments = item.comments
					end
				%>
				<div class="checklist-row">
					<label for="checklist_item_<%= item.id %>" <%= "class=strikethrough" if environment != "projects" && item.applicable == false %>>
						<% if environment == "projects" %>
							<%= item.title %>
						<% else %>
							<%= toggle_item_checkbox(item) %>
						<% end %>
						<% if user_signed_in? && current_user.show_timestamps == true %>
							<%= "<span class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</span>".html_safe unless item.modified_by.blank? %>
						<% end %>
					</label>
					<div class="clearfix"></div>
					<% if user_signed_in? %>
						<div class="actions">
							<% if environment == "projects" %>
								<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: item.id, checklist_item_type: 'Project'), class: "fancybox", data: { fancybox_type: "iframe" } %>
								<% if item.comments_count > 0 %>
									&nbsp; <strong>|</strong> &nbsp;
									<a class="comments-toggle_<%= item.id %>" href="#" onclick="commentsToggle(<%= item.id %>,<%= item.comments_count %>); return false;">Hide Comments (<%= item.comments_count %>)</a>
								<% end %>
							<% else %>
								<%= link_to toggle_applicable(item), toggle_applicable_checklist_path(item), remote: true, id: "checklist_item_applicable_#{item.id}" %>
								&nbsp; <strong>|</strong> &nbsp;
								<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: item.id, checklist_item_type: 'Item'), class: "fancybox", data: { fancybox_type: "iframe" } %>
								<% if @item_comments.count > 0 %>
									&nbsp; <strong>|</strong> &nbsp;
									<a class="comments-toggle_<%= item.id %>" href="#" onclick="commentsToggle(<%= item.id %>,<%= @item_comments.count %>); return false;">Hide Comments (<%= @item_comments.count %>)</a>
								<% end %>
							<% end %>
						</div>
						<div class="clearfix"></div>
					<% end %>
					<div class="comments comments_block_<%= item.id %>">
						<% @item_comments.each do |c| %>
							<% if (environment == "projects" && c.checklist_item_id == item.id) || c.checklist_item_type == 'Item' %>
								<div class="comment well">
									<div class="heading">
										<%= c.author %> said on <%= c.updated_at.strftime('%B %e, %Y @ %l:%M %P') %>
										<% if user_signed_in? %>
											&nbsp;|&nbsp;
											<%= link_to image_tag('/assets/iconEdit.png'), edit_comment_path(c.id), class: "fancybox", data: { fancybox_type: "iframe" } %>
											<%= link_to image_tag('/assets/iconDelete.png'), c, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
										<% end %>
									</div>
									<%= c.comment.html_safe %>
								</div>
							<% end %>
						<% end %>
					</div>
					<div class="clearfix"></div>
				</div>
			<% end %>
		<% end %>
	</div>
<% end %>
<div class="clearfix"></div>

app/views/checklists/toggle_applicable.js.erb
$("#checklist_item_applicable_<%= @item.id %>").parent().parent().fadeOut(250, function(){
	if(<%= @item.applicable %> == false){
		$("label[for='checklist_item_<%= @item.id %>']").addClass("strikethrough").find("input").attr("disabled","disabled");
		$(this).find("#checklist_item_applicable_<%= @item.id %>").html("<%= toggle_applicable(@item) %>");
		$(this).fadeIn(250);
	}else if(<%= @item.applicable %> == true){
		$("label[for='checklist_item_<%= @item.id %>']").removeClass("strikethrough").find("input").removeAttr("disabled");
		$(this).find("#checklist_item_applicable_<%= @item.id %>").html("<%= toggle_applicable(@item) %>");
		$(this).fadeIn(250);
	}
});

app/views/checklists/toggle_tool.js.erb
$("#checklist_tool_<%= @tool.id %>").fadeOut(250, function(){
	$(this).html("<%= toggle_tool_image(@tool) %>").fadeIn(250);
});