config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items do
    get 'send_patch_list', on: :member
    post 'prioritize', on: :member
  end
  
  resources :comments
  
  match '/report', to: 'report#report', via: :get
  match '/report', to: 'report#report_email', via: :post
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  def index
    @archive = params[:archive]
    if @archive == 'true'
      @archive_status = 'true'
      @releases = Release.paginate(page: params[:page], :per_page => 15, :order => "release_date DESC, title ASC")
    else
      @archive_status = 'false'
      @releases = Release.paginate(page: params[:page], :per_page => 15, :conditions => ["archive = ?", false], :order => "release_date DESC, title ASC")
    end
  end
  
  def new
    @release = Release.new
    @users = User.find(:all, select: "id, name", order: "name ASC").collect
  end
  
  def create
    @release = Release.new(params[:release])
    if @release.save
      @checklist_tools = ReleaseData.find(:all, conditions: "section LIKE 'tools'", order: "priority ASC")
      @checklist_tools.each do |t|
        @tool = ChecklistTool.new(release_id: @release.id, release_data_id: t.id, value: false)
        @tool.save
      end
      @checklist_items = ReleaseData.find(:all, conditions: "section NOT LIKE 'tools'", order: "section ASC, priority ASC")
      @checklist_items.each do |i|
        @item = ChecklistItem.new(release_id: @release.id, release_data_id: i.id, environment: i.section, value: false, applicable: true)
        @item.save
      end
      if @release.archive == true
        flash[:success] = "\"#{@release.title}\" has been created."
        flash[:info] = "\"#{@release.title}\" has been archived."
      else
        flash[:success] = "\"#{@release.title}\" has been created."
      end
      redirect_to releases_path
    else
      @users = User.find(:all, select: "id, name", order: "name ASC").collect
      render 'new'
    end
  end
  
  def edit
    @release = Release.find(params[:id])
    @users = User.find(:all, select: "id, name", order: "name ASC").collect
  end
  
  def update
    @release = Release.find(params[:id])
    if @release.update_attributes(params[:release])
      if @release.archive == true
        flash[:success] = "\"#{@release.title}\" has been updated."
        flash[:info] = "\"#{@release.title}\" has been archived."
      else
        flash[:success] = "\"#{@release.title}\" has been updated."
      end
      redirect_to releases_path
    else
      @users = User.find(:all, select: "id, name", order: "name ASC").collect
      render 'edit'
    end
  end
  
  def destroy
    @release = Release.find(params[:id])
    @release.destroy
    flash[:success] = "\"#{@release.title}\" has been deleted."
    redirect_to releases_path
  end
end

app/views/releases/_form.html.erb
<%= form_for(@release) do |f| %>
	<%= render 'shared/error_messages', :object => @release %>
	
	<%= f.label :title, "Title*" %>
	<%= f.text_field :title, placeholder: "Enter the release name...", class: "input-xxlarge" %>
	
	<%= f.label :contact, "Primary Contact*" %>
	<%= f.select :contact, options_for_select(@users.each { |user| [ user.name, user.name ] }, selected: @release.contact), { include_blank: 'Unassigned' } %>
	
	<%= f.label :backup_contact, "Backup Contact*" %>
	<%= f.select :backup_contact, options_for_select(@users.each { |user| [ user.name, user.name ] }, selected: @release.backup_contact), { include_blank: 'Unassigned' } %>
	
	<%= f.label :release_date, "Release Date*" %>
	<%= f.text_field :release_date, "data-behaviour" => "datepicker", class: "input-medium" %>
	
	<%= f.label :code_cutoff_date, "Code Cutoff Date*" %>
	<%= f.text_field :code_cutoff_date, "data-behaviour" => "datepicker", class: "input-medium" %>
	
	<label class="checkbox">
    	<%= f.check_box :archive %> Archive?
    </label>
    
    <%= f.hidden_field :modified_by, value: current_user.email %>
	
	<div class="form-action-buttons">
		<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<div class="btn-cancel">
			<%= link_to "Cancel", :back, class: "btn btn-large" %>
		</div>
	</div>
<% end %>

app/views/releases/_releases_detail.html.erb
<section id="detail-view" class="data-list">
	<% @releases.each do |release| %>
		<article class="data">
			<% if release.archive == true %>
				<div class="label label-warning archive-tag">
					Archived
				</div>
			<% end %>
			<div class="release-headline">
				<div class="release-title">
					<%= release.title %>
					<% if user_signed_in? && release.release_date == Date.today %>
						<div class="send-report">
							[<%= link_to "Send Post Release Report", report_path(id: release.id) %>]
						</div>
					<% end %>
				</div>
				<div class="release-actions">
					<% if user_signed_in? %>
						<%= link_to "Update", edit_release_path(release), class: "btn btn-small btn-primary" %>
						<%= link_to "Delete", release, method: :delete, data: { confirm: "Are you sure you want to delete #{release.title}?" }, class: "btn btn-small" %>
					<% end %>
				</div>
				<div class="release-pages">
					<%= link_to "Checklist", checklist_path(release.id), class: "btn btn-small btn-primary" %>
					<%= link_to "Release List", release_items_path(id: release.id), class: "btn btn-small" %>
				</div>
			</div>
			<div class="release-item-details">
				<div class="left-column">
					<span class="headings">Primary Contact:</span> <%= (release.contact != '') ? release.contact : 'Unassigned' %><br />
					<span class="headings">Backup Contact:</span> <%= (release.backup_contact != '') ? release.backup_contact : 'Unassigned' %><br />
					<span class="headings">Release Date:</span> <%= (release.release_date) ? release.release_date.strftime('%B %e, %Y') : 'Not Specified' %><br />
					<span class="headings">Code Cutoff Date:</span> <%= (release.code_cutoff_date) ? release.code_cutoff_date.strftime('%B %e, %Y') : 'Not Specified' %>
				</div>
				<div class="right-column">
					<span class="headings">Status:</span> <%= (release.archive == true) ? "archived" : "active" %><br />
					<span class="headings">Created On:</span> <%= release.created_at.strftime('%B %e, %Y @ %l:%M %P') %><br />
					<span class="headings">Updated On:</span> <%= release.updated_at.strftime('%B %e, %Y @ %l:%M %P') %>
				</div>
			</div>
		</article>
	<% end %>
</section>

app/views/releases/_releases_list.html.erb
<section id="list-view" class="data-list">
	<% @releases.each do |release| %>
		<article class="data">
			<% if release.archive == true %>
				<div class="label label-warning archive-tag">
					Archived
				</div>
			<% end %>
			<div class="release-headline">
				<div class="release-title">
					<%= release.title %>
					<% if user_signed_in? && release.release_date == Date.today %>
						<div class="send-report">
							[<%= link_to "Send Post Release Report", report_path(id: release.id) %>]
						</div>
					<% end %>
				</div>
				<div class="release-actions">
					<% if user_signed_in? %>
						<%= link_to "Update", edit_release_path(release) %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "Delete", release, method: :delete, data: { confirm: "Are you sure you want to delete #{release.title}?" } %>
					<% end %>
				</div>
				<div class="release-pages">
					<%= link_to "Checklist", checklist_path(release.id) %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "Release List", release_items_path(id: release.id) %>
				</div>
			</div>
		</article>
	<% end %>
</section>

app/views/releases/edit.html.erb
<%= provide(:title, "Update Release: #{@release.title}") %>

<h1>Update Release: <%= @release.title %></h1>

<% if @release.archive == true %>
	<div class="label label-warning archive-tag">Archived</div>
<% end %>

<%= render 'form' %>

app/views/releases/index.html.erb
<% provide(:title, 'Releases') %>
<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			padding: 20,
			scrolling: 'no',
			maxWidth: 700
		});
	});
</script>

<h1>
	Releases<br />
	<% if @archive_status == 'false' %>
		<%= link_to "View All", { :controller => 'releases', :action => 'index', :archive => true }, class: "btn btn-small archive-toggle" %>
	<% else %>
		<%= link_to "Hide Archived", { :controller => 'releases', :action => 'index', :archive => false }, class: "btn btn-small archive-toggle" %>
	<% end %>
</h1>

<% if user_signed_in? %>
	<%= link_to "Add New Release", new_release_path, class: "btn btn-large btn-primary btn-new-release-top" %>
<% end %>

<% if @releases.empty? %>
	<h2>No releases have been created yet.</h2>
<% else %>
	<div class="releases">
		<div class="pagination-controls-container">
			<%= will_paginate @releases, previous_label: "<", next_label: ">", inner_window: 1, outer_window: 1 %>
			<div class="controls">
				Views: <%= link_to "Detail", "#", class: "btn btn-small btn-primary detail-view-link" %> <%= link_to "List", "#", class: "btn btn-small list-view-link" %>
			</div>
		</div>
		<%= render 'releases_detail' %>
		<%= render 'releases_list' %>
		<div class="pagination-controls-container">
			<%= will_paginate @releases, previous_label: "<", next_label: ">", inner_window: 1, outer_window: 1 %>
			<div class="controls">
				Views: <%= link_to "Detail", "#", class: "btn btn-small btn-primary detail-view-link" %> <%= link_to "List", "#", class: "btn btn-small list-view-link" %>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
<% end %>

<% if user_signed_in? %>
	<%= link_to "Add New Release", new_release_path, class: "btn btn-large btn-primary btn-new-release-bottom" %>
<% end %>

app/views/releases/new.html.erb
<%= provide(:title, 'Create New Release') %>

<h1>Create New Release</h1>

<%= render 'form' %>